AllCops:
    TargetRubyVersion: 2.6

Layout/IndentationWidth:
    Width: 4

Metrics/LineLength:
    Max: 89

Metrics/MethodLength:
    Max: 25

Naming/AsciiIdentifiers:
    Enabled: false

Naming/FileName:
    Enabled: false

Naming/MethodName:
    Enabled: false

Naming/VariableName: 
    Enabled: false

Style/AsciiComments:
    AllowedChars: [☑️ , á, é, í, ó, ú, Á, É, Í, Ó, Ú, ñ]

Style/FrozenStringLiteralComment:
    EnforcedStyle: never
