Layout/IndentationWidth:
        Width: 4

Style/AsciiComments:
        AllowedChars: [☑️ , á, é, í, ó, ú, Á, É, Í, Ó, Ú]

AllCops:
  TargetRubyVersion: 2.5

Style/FrozenStringLiteralComment:
        EnforcedStyle: never

Naming/AsciiIdentifiers:
        Enabled: false
