AllCops:
    NewCops: enable
    TargetRubyVersion: 2.6

Style/Documentation:
    Enabled: false

Layout/IndentationWidth:
    Width: 4

Layout/LineLength:
    Max: 89
    AutoCorrect: true

Metrics/AbcSize:
    Max: 30

Metrics/ClassLength:
    Enabled: false

Metrics/CyclomaticComplexity:
    Max: 10

Metrics/MethodLength:
    Max: 50

Metrics/PerceivedComplexity:
    Max: 10

Naming/AsciiIdentifiers:
    Enabled: false

Naming/FileName:
    Enabled: false

Naming/MethodName:
    Enabled: false

Naming/VariableName: 
    Enabled: false

Style/AsciiComments:
    AllowedChars: [☑️, á, é, í, ó, ú, ü, ñ, Á, É, Í, Ó, Ú, Ü, Ñ, ¬]


Style/FrozenStringLiteralComment:
    EnforcedStyle: never
